export const packageTypes = [
  { name: "Bag (BG)", code: "BG" },
  { name: "Bale, compressed (BL)", code: "BL" },
  { name: "Bar (BR)", code: "BR" },
  { name: "Barrel (BA)", code: "BA" },
  { name: "Basket (BK)", code: "BK" },
  { name: "Board (BD)", code: "BD" },
  { name: "Box (BX)", code: "BX" },
  { name: "Bulk, liquid (VL)", code: "VL" },
  { name: "Bundle (BE)", code: "BE" },
  { name: "Cage (CG)", code: "CG" },
  { name: "Carton (CT)", code: "CT" },
  { name: "Case (CS)", code: "CS" },
  { name: "Coffin (CJ)", code: "CJ" },
  { name: "Container, not otherwise specified as transport equipment (CN)", code: "CN" },
  { name: "Crate (CR)", code: "CR" },
  { name: "Crate, milk (MC)", code: "MC" },
  { name: "Cylinder (CY)", code: "CY" },
  { name: "Drum (DR)", code: "DR" },
  { name: "Intermediate bulk container (WA)", code: "WA" },
  { name: "Intermediate bulk container, metal (WF)", code: "WF" },
  { name: "Intermediate bulk container, plywood (ZX)", code: "ZX" },
  { name: "Keg (KG)", code: "KG" },
  { name: "Package (PK)", code: "PK" },
  { name: "Pail (PL)", code: "PL" },
  { name: "Pallet (PX)", code: "PX" },
  { name: "Parcel (PC)", code: "PC" },
  { name: "Reefer (RF)", code: "RF" },
  { name: "Reel (RL)", code: "RL" },
  { name: "Roll (RO)", code: "RO" },
  { name: "Sheet (ST)", code: "ST" },
  { name: "Skid (SI)", code: "SI" },
  { name: "Suitcase (SU)", code: "SU" },
  { name: "Tank, cylindrical (TY)", code: "TY" },
  { name: "Tank, rectangular (TK)", code: "TK" },
  { name: "Trailer, for Boats (TA)", code: "TA" },
  { name: "Tube (TU)", code: "TU" },
  { name: "Unpacked or unpackaged (NE)", code: "NE" },
  { name: "Vehicle (VN)", code: "VN" },
];
